version: '3.7'

services:
  web:
    build: .
    command: sh ./docker-web-script.sh
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - ${OPEN_PORT}:${DJANGO_PORT}
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data/
    env_file:
      - .env


volumes:
  postgres_data:
